# these have been copied into helm-kind/templates directory
apiVersion: apps/v1
kind: Service
metadata:
  name: app
spec:
  type: NodePort
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
