apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: "{{ .Values.name }}"
        imagePullPolicy: Never
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20M