apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: {{ .Values.nodePort }}
